### ISSUE TITLE
Cannot delete ODO projects

### ISSUE THREAD

**Issue by ssh24** [eclipse/codewind#1201]
**Description:**
ODO projects are failing to delete with the following error:
```
19/11/19 15:50:21 mypy] [TRACE] Deleting project e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:21 mypy] [INFO] containerDelete: Kill running processes and remove container... 
[19/11/19 15:50:21 mypy] [INFO] Project ID:        e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:21 mypy] [INFO] Project Location:  /codewind-workspace/mypy
[19/11/19 15:50:21 mypy] [INFO] Project Type:      odo
[19/11/19 15:50:21 mypy] [INFO] Project Container: cw-mypy-app-1-zmmv8

[19/11/19 15:50:21 mypy] [TRACE] pod/cw-mypy-app-1-zmmv8

[19/11/19 15:50:21 mypy] [INFO] projectInfo.deploymentRegistry: undefined
[19/11/19 15:50:21 mypy] [TRACE] 
Removing odo application

[19/11/19 15:50:21 mypy] [TRACE] 
Step 1 of 2:

[19/11/19 15:50:21 mypy] [TRACE] Stopping monitor app log

[19/11/19 15:50:22 mypy] [ERROR] containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (22458) - No such process

[19/11/19 15:50:22 mypy] [TRACE] 
Step 2 of 2:

[19/11/19 15:50:22 mypy] [TRACE] - Deleting odo component: cw-mypy

[19/11/19 15:50:22 mypy] [TRACE] This component has following urls that will be deleted with component

[19/11/19 15:50:22 mypy] [TRACE] URL named cw-mypy with host cw-mypy-app-che.9.46.125.238.nip.io having protocol http at port 8080

[19/11/19 15:50:22 mypy] [TRACE]  •  Deleting component cw-mypy  ...

[19/11/19 15:50:22 mypy] [TRACE]  ✓  Deleting component cw-mypy [163ms]
 ✓  Component cw-mypy from application app has been deleted

[19/11/19 15:50:22 mypy] [TRACE]  ✓  Config for the Component cw-mypy has been deleted
- Successfully deleted odo component: cw-mypy

[19/11/19 15:50:22 Turbine] [TRACE] [mypy] Running processes:
[19/11/19 15:50:22 Turbine] [TRACE] [mypy]    PID   PPID   PGID COMMAND
     1      0      1 sh
    82      1      1 npm
    94     82      1 npm-start.sh
    95     94      1 npm
   107     95      1 node
 17225      0  17225 bash
 22029      1  20237 kubectl
 22423    107  22423 bash
 22496    107      1 ps
 22498  22423  22423 tee

[19/11/19 15:50:22 mypy] [TRACE] 
Successfully removed odo application


[19/11/19 15:50:22 Turbine] [INFO] Removing extension project handler e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:22 mypy] [INFO] Removing dangling images for e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:22 mypy] [INFO] Project info cache is {}
[19/11/19 15:50:22 mypy] [INFO] Successfully deleted e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:22 Turbine] [INFO] Removing project logs directory
[19/11/19 15:50:22 FileWatcher.js] [DEBUG] Portal's event listener: projectDeletion
[19/11/19 15:50:22 FileWatcher.js] [DEBUG] Portal's event listener: {"operationId":"a37d3a1d744c74c5ab84e018fb4c833b","projectID":"e4610940-0ae3-11ea-a670-b3bcf1b339b4","status":"failed","error":"Failed to remove project e4610940-0ae3-11ea-a670-b3bcf1b339b4"}
[19/11/19 15:50:22 FileWatcher.js] [ERROR] projectDeletion: failed (project: {
  "operationId": "a37d3a1d744c74c5ab84e018fb4c833b",
  "projectID": "e4610940-0ae3-11ea-a670-b3bcf1b339b4",
  "status": "failed",
  "error": "Failed to remove project e4610940-0ae3-11ea-a670-b3bcf1b339b4"
})
[19/11/19 15:50:22 FileWatcher.js] [DEBUG] projectDeletion: failed (project e4610940-0ae3-11ea-a670-b3bcf1b339b4)
[19/11/19 15:50:22 FileWatcher.js] [TRACE] projectDeletion: failed (project: {
  "operationId": "a37d3a1d744c74c5ab84e018fb4c833b",
  "projectID": "e4610940-0ae3-11ea-a670-b3bcf1b339b4",
  "status": "failed",
  "error": "Failed to remove project e4610940-0ae3-11ea-a670-b3bcf1b339b4"
})
[19/11/19 15:50:22 WebSocket.js] [DEBUG] Sending message to clients: {"type":"watchChanged","projects":[{"changeType":"delete","projectID":"e4610940-0ae3-11ea-a670-b3bcf1b339b4"}]}
[19/11/19 15:50:22 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] e4610940-0ae3-11ea-a670-b3bcf1b339b4: Failed to remove project e4610940-0ae3-11ea-a670-b3bcf1b339b4
[19/11/19 15:50:22 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] e4610940-0ae3-11ea-a670-b3bcf1b339b4: Error: ENOTEMPTY: directory not empty, rmdir '/codewind-workspace/.logs/mypy-e4610940-0ae3-11ea-a670-b3bcf1b339b4'
[19/11/19 15:50:22 Turbine] [INFO] e4610940-0ae3-11ea-a670-b3bcf1b339b4: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "a37d3a1d744c74c5ab84e018fb4c833b",
  "projectID": "e4610940-0ae3-11ea-a670-b3bcf1b339b4",
  "status": "failed",
  "error": "Failed to remove project e4610940-0ae3-11ea-a670-b3bcf1b339b4"
}
[19/11/19 15:50
```

**Che version**: 7.3.1

**Steps to reproduce:**
1. Create a odo project
2. Wait for it to be started
3. Delete the app

**Comment by elsony** [comment]
@ssh24 Is this for master only or it also happens on 0.6.0?

**Comment by ssh24** [comment]
I saw it on master. Testing on 0.6.0 now

**Comment by ssh24** [comment]
Seeing it on 0.6.0 as well. Definite stopship:
```
19/11/19 16:06:44 odopy] [TRACE] Deleting project 320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:44 odopy] [INFO] containerDelete: Kill running processes and remove container... 
[19/11/19 16:06:44 odopy] [INFO] Project ID:        320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:44 odopy] [INFO] Project Location:  /codewind-workspace/odopy
[19/11/19 16:06:44 odopy] [INFO] Project Type:      odo
[19/11/19 16:06:44 odopy] [INFO] Project Container: cw-odopy-app-1-kth4k

[19/11/19 16:06:44 odopy] [TRACE] pod/cw-odopy-app-1-kth4k

[19/11/19 16:06:44 odopy] [INFO] projectInfo.deploymentRegistry: docker-registry.default.svc:5000/che
[19/11/19 16:06:44 odopy] [TRACE] 
Removing odo application

[19/11/19 16:06:44 odopy] [TRACE] 
Step 1 of 2:

[19/11/19 16:06:44 odopy] [TRACE] Stopping monitor app log

[19/11/19 16:06:45 odopy] [ERROR] containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (19046) - No such process

[19/11/19 16:06:45 odopy] [TRACE] 
Step 2 of 2:

[19/11/19 16:06:45 odopy] [TRACE] - Deleting odo component: cw-odopy

[19/11/19 16:06:45 odopy] [TRACE] This component has following urls that will be deleted with component

[19/11/19 16:06:45 odopy] [TRACE] URL named cw-odopy with host cw-odopy-app-che.9.46.125.238.nip.io having protocol http at port 8080

[19/11/19 16:06:45 odopy] [TRACE]  •  Deleting component cw-odopy  ...

[19/11/19 16:06:45 Turbine] [TRACE] [odopy] Running processes:
[19/11/19 16:06:45 Turbine] [TRACE] [odopy]    PID   PPID   PGID COMMAND
     1      0      1 sh
    12      1      1 root-watcher.sh
    46     12      1 buildah
    81      1      1 npm
    92     81      1 npm-start.sh
    93     92      1 npm
   105     93      1 node
  4301     46      1 exe
  4332   4301   4332 sh
  9644      0   9644 bash
 16047      1   3678 kubectl
 18867   4332   4332 ibm-java.bin
 18990    105  18990 bash
 19041  18867   4332 gzip
 19062  18990  18990 bash
 19098  19062  18990 odo
 19099  19062  18990 tee
 19123    105      1 ps

[19/11/19 16:06:45 odopy] [TRACE]  ✓  Deleting component cw-odopy [158ms]
 ✓  Component cw-odopy from application app has been deleted

[19/11/19 16:06:45 odopy] [TRACE]  ✓  Config for the Component cw-odopy has been deleted

[19/11/19 16:06:46 odopy] [TRACE] - Successfully deleted odo component: cw-odopy

[19/11/19 16:06:46 Turbine] [INFO] Removing extension project handler 320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:46 odopy] [TRACE] 
Successfully removed odo application


[19/11/19 16:06:46 odopy] [INFO] Removing dangling images for 320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:46 odopy] [INFO] Project info cache is {}
[19/11/19 16:06:46 odopy] [INFO] Successfully deleted 320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:46 Turbine] [INFO] Removing project logs directory
[19/11/19 16:06:46 FileWatcher.js] [DEBUG] Portal's event listener: projectDeletion
[19/11/19 16:06:46 FileWatcher.js] [DEBUG] Portal's event listener: {"operationId":"fcdf5259e946c30867a39ccfdadc5d59","projectID":"320b2b10-0ae6-11ea-b87e-fd9dd268b170","status":"failed","error":"Failed to remove project 320b2b10-0ae6-11ea-b87e-fd9dd268b170"}
[19/11/19 16:06:46 FileWatcher.js] [ERROR] projectDeletion: failed (project: {
  "operationId": "fcdf5259e946c30867a39ccfdadc5d59",
  "projectID": "320b2b10-0ae6-11ea-b87e-fd9dd268b170",
  "status": "failed",
  "error": "Failed to remove project 320b2b10-0ae6-11ea-b87e-fd9dd268b170"
})
[19/11/19 16:06:46 FileWatcher.js] [DEBUG] projectDeletion: failed (project 320b2b10-0ae6-11ea-b87e-fd9dd268b170)
[19/11/19 16:06:46 FileWatcher.js] [TRACE] projectDeletion: failed (project: {
  "operationId": "fcdf5259e946c30867a39ccfdadc5d59",
  "projectID": "320b2b10-0ae6-11ea-b87e-fd9dd268b170",
  "status": "failed",
  "error": "Failed to remove project 320b2b10-0ae6-11ea-b87e-fd9dd268b170"
})
[19/11/19 16:06:46 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] 320b2b10-0ae6-11ea-b87e-fd9dd268b170: Failed to remove project 320b2b10-0ae6-11ea-b87e-fd9dd268b170
[19/11/19 16:06:46 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] 320b2b10-0ae6-11ea-b87e-fd9dd268b170: Error: ENOTEMPTY: directory not empty, rmdir '/codewind-workspace/.logs/odopy-320b2b10-0ae6-11ea-b87e-fd9dd268b170'
[19/11/19 16:06:46 Turbine] [INFO] 320b2b10-0ae6-11ea-b87e-fd9dd268b170: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "fcdf5259e946c30867a39ccfdadc5d59",
  "projectID": "320b2b10-0ae6-11ea-b87e-fd9dd268b170",
  "status": "failed",
  "error": "Failed to remove project 320b2b10-0ae6-11ea-b87e-fd9dd268b170"
```

**Comment by maysunfaisal** [comment]
probably run this cmd on tthe PFE terminal when you have a project https://github.com/eclipse/codewind-odo-extension/blob/master/scripts/odo-functions.sh#L72

could be an issue with  ODO

**Comment by GeekArthur** [comment]
Cause is here: `containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (22458) - No such process.` What’s your PFE SHA? This issue should be fixed by my latest PR, you can try the latest 0.6.0 to verify.

**Comment by GeekArthur** [comment]
The latest PFE SHA for 0.6.0 is `sha256:8778d4e2ee9816ec26da3a4ec683275e1dd1194f7fe8061e82d5b30cd72500ad` on our Docker Hub, I am using this one and it works for me

**Comment by ssh24** [comment]
I am still seeing this on 0.6.0. My PFE SHA is the same `sha256:8778d4e2ee9816ec26da3a4ec683275e1dd1194f7fe8061e82d5b30cd72500ad`. I noticed it was working for nodejs earlier but now all 3 project types are failing.

Looks like the issue is here:
```
[19/11/19 17:04:13 odoperl] [TRACE] Stopping monitor app log

[19/11/19 17:04:13 odoperl] [ERROR] containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (31583) - No such process
```

**Comment by GeekArthur** [comment]
See my comments above, it's same thing that I mention before. I don't have your cluster so I can't debug this for you, you can leave your cluster credentials here so that I can help you find the issue in your cluster to see why the process is not in your cluster.

**Comment by GeekArthur** [comment]
Also I don't think this is a `stopship` issue given both my cluster and Len's cluster can't reproduce this.

**Comment by maysunfaisal** [comment]
Fails for me as well

Installed Che 7.3.1 with operator 7.3.1 today at 12pm. Installed CW 0.6.0 after SC update from John.

```
[19/11/19 18:16:30 odono1] [INFO] operationId: e7f6171bd5c961bcd360601910d0ff91
[19/11/19 18:16:30 odono1] [INFO] containerDelete: Kill running processes and remove container... 
[19/11/19 18:16:30 odono1] [INFO] Project ID:        36d494d0-0af8-11ea-b498-699f24eb89c4
[19/11/19 18:16:30 odono1] [INFO] Project Location:  /codewind-workspace/odono1
[19/11/19 18:16:30 odono1] [INFO] Project Type:      odo
[19/11/19 18:16:30 odono1] [INFO] Project Container: cw-odono1-app-1-r72gn

[19/11/19 18:16:30 odono1] [INFO] projectInfo.deploymentRegistry: undefined
[19/11/19 18:16:31 odono1] [ERROR] containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (29131) - No such process

[19/11/19 18:16:31 Turbine] [INFO] Removing extension project handler 36d494d0-0af8-11ea-b498-699f24eb89c4
[19/11/19 18:16:31 odono1] [INFO] Removing dangling images for 36d494d0-0af8-11ea-b498-699f24eb89c4
[19/11/19 18:16:31 odono1] [INFO] Project info cache is {"/file-watcher/fwdata/projects/de71c7e0-0af7-11ea-b498-699f24eb89c4/de71c7e0-0af7-11ea-b498-699f24eb89c4.json":"{\"projectID\":\"de71c7e0-0af7-11ea-b498-699f24eb89c4\",\"projectType\":\"docker\",\"location\":\"/codewind-workspace/gg1\",\"autoBuildEnabled\":true,\"startMode\":\"run\",\"appPorts\":[],\"language\":\"go\",\"ignoredPaths\":[\"/.project\",\"*/node_modules*\",\"*/.git/*\",\"*/.DS_Store\",\"*/*.swp\",\"*/*.swx\",\"*/4913\",\"/load-test*\",\"*/.dockerignore\",\"*/.gitignore\",\"*/*~\",\"/.settings\"],\"isHttps\":false,\"appBaseURL\":\"http://cw-gg1-de71c7e0-0af7-11ea-b498-che-che.9.37.222.212.nip.io\",\"sentProjectInfo\":true}"}
[19/11/19 18:16:31 odono1] [INFO] Successfully deleted 36d494d0-0af8-11ea-b498-699f24eb89c4
[19/11/19 18:16:31 Turbine] [INFO] Removing project logs directory
[19/11/19 18:16:31 FileWatcher.js] [ERROR] projectDeletion: failed (project: {
  "operationId": "e7f6171bd5c961bcd360601910d0ff91",
  "projectID": "36d494d0-0af8-11ea-b498-699f24eb89c4",
  "status": "failed",
  "error": "Failed to remove project 36d494d0-0af8-11ea-b498-699f24eb89c4"
})
[19/11/19 18:16:31 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] 36d494d0-0af8-11ea-b498-699f24eb89c4: Failed to remove project 36d494d0-0af8-11ea-b498-699f24eb89c4
[19/11/19 18:16:31 Turbine] [ERROR] [File Name: /file-watcher/server/dist/utils/logger.js | Function Name: logProjectError | Line Number: 202] 36d494d0-0af8-11ea-b498-699f24eb89c4: Error: ENOTEMPTY: directory not empty, rmdir '/codewind-workspace/.logs/odono1-36d494d0-0af8-11ea-b498-699f24eb89c4'
[19/11/19 18:16:31 Turbine] [INFO] 36d494d0-0af8-11ea-b498-699f24eb89c4: Emitting event 
 message: projectDeletion
 data: {
  "operationId": "e7f6171bd5c961bcd360601910d0ff91",
  "projectID": "36d494d0-0af8-11ea-b498-699f24eb89c4",
  "status": "failed",
  "error": "Failed to remove project 36d494d0-0af8-11ea-b498-699f24eb89c4"
}
[19/11/19 18:16:33 Turbine] [INFO] No dangling images were found.

```

The image is gone but the dir is still present in the PFE workspace
```
[root@codewind-workspacetcxzwdkcgo37wzjx-7f8854c699-x4sns /]# buildah images
REPOSITORY                                 TAG                    IMAGE ID       CREATED         SIZE
localhost/liberty-app-cache                latest                 44bfbd13460a   6 minutes ago   885 MB
localhost/cw-gg1-de71c7e0-0af7-11ea-b498   latest                 eecb9e94c9f0   6 minutes ago   831 MB
localhost/spring-app-cache                 latest                 5919cfbd7524   7 minutes ago   418 MB
docker.io/library/golang                   latest                 54e71dcafb7c   2 weeks ago     823 MB
docker.io/library/ibmjava                  8-sfj                  d90eeb02c4a7   2 weeks ago     170 MB
docker.io/library/websphere-liberty        19.0.0.3-webProfile7   c6892fcebf3c   2 months ago    468 MB
docker.io/library/hello-world              latest                 fce289e99eb9   10 months ago   6.14 KB
[root@codewind-workspacetcxzwdkcgo37wzjx-7f8854c699-x4sns /]# cd /codewind-workspace/
[root@codewind-workspacetcxzwdkcgo37wzjx-7f8854c699-x4sns codewind-workspace]# ls -la
total 0
drwxrwxrwx. 10 root root 126 Nov 19 18:12 .
drwxr-xr-x.  1 root root  82 Nov 19 18:06 ..
drwxr-xr-x.  3 root root  45 Nov 19 18:10 .appsody
drwxrwxr-x.  2 root root  55 Nov 19 18:10 .config
drwxrwxr-x.  4 root root  70 Nov 19 18:06 .extensions
drwxr-xr-x.  4 root root 181 Nov 19 18:12 .logs
drwxrwxr-x.  2 root root 102 Nov 19 18:12 .projects
drwxrwxr-x.  2 root root   6 Nov 19 18:12 cw-temp
drwxrwxr-x.  3 root root  89 Nov 19 18:10 gg1
drwxrwxr-x.  6 root root 153 Nov 19 18:16 odono1
```

**Comment by ssh24** [comment]
FWIW, the automation test on ODO is also able to catch it. Leaving it to the leads to decide if it is stopship or not.

**Comment by GeekArthur** [comment]
PR has been merged, @ssh24 @maysunfaisal you can verify it once the latest 0.6.0 PFE image has the fix.

**Comment by ssh24** [comment]
Still seeing it on 0.6.0. 
```
[19/11/19 21:11:01 mypy] [INFO] pingInTransitApplications: Application state for project c22db8a0-0b10-11ea-99ef-dd9dd460ca25 has changed from starting to started
[19/11/19 21:11:13 mypy] [INFO] operationId: 8d5dccb684934d183dd10091516d3475
[19/11/19 21:11:13 mypy] [INFO] containerDelete: Kill running processes and remove container... 
[19/11/19 21:11:13 mypy] [INFO] Project ID:        c22db8a0-0b10-11ea-99ef-dd9dd460ca25
[19/11/19 21:11:13 mypy] [INFO] Project Location:  /codewind-workspace/mypy
[19/11/19 21:11:13 mypy] [INFO] Project Type:      odo
[19/11/19 21:11:13 mypy] [INFO] Project Container: cw-mypy-app-1-z7fgx

[19/11/19 21:11:13 mypy] [INFO] projectInfo.deploymentRegistry: undefined
[19/11/19 21:11:14 mypy] [ERROR] containerDelete : 588 | /codewind-workspace/.extensions/codewind-odo-extension/odo-extension-entrypoint.sh: line 123: kill: (22524) - No such process

[19/11/19 21:11:14 Turbine] [INFO] Removing extension project handler c22db8a0-0b10-11ea-99ef-dd9dd460ca25
[19/11/19 21:11:14 mypy] [INFO] Removing dangling images for c22db8a0-0b10-11ea-99ef-dd9dd460ca25
[19/11/19 21:11:14 mypy] [INFO] Project info cache is {}
[19/11/19 21:11:14 mypy] [INFO] Successfully deleted c22db8a0-0b10-11ea-99ef-dd9dd460ca25
[19/11/19 21:11:14 Turbine] [INFO] Removing project logs directory
[19/11/19 21:11:14 FileWatcher.js] [ERROR] projectDeletion: failed (project: {
  "operationId": "8d5dccb684934d183dd10091516d3475",
  "projectID": "c22db8a0-0b10-11ea-99ef-dd9dd460ca25",
  "status": "failed",
  "error": "Failed to remove project c22db8a0-0b10-11ea-99ef-dd9dd460ca25"
})
```
Maybe the image has not been published yet?

**Comment by maysunfaisal** [comment]
can you exec and see if Jingfu's changes have been picked up? I dont see it yet

**Comment by GeekArthur** [comment]
@ssh24 Yea, our 0.6.0 PFE image still uses SHA sha256:8778d4e2ee9816ec26da3a4ec683275e1dd1194f7fe8061e82d5b30cd72500ad which doesn't include my fix, let me ask committer to manually trigger to build, then we all good to test.

**Comment by elsony** [comment]
@GeekArthur Fix for 0.6.0 has been merged.  I leave this one in progress for putting the same change into master.

**Comment by ssh24** [comment]
It worked on 0.6.0 now. Looks like the issue was with how the process was being closed. **Verified** but will keep it on till it is fixed on master.

**Comment by GeekArthur** [comment]
I log in to Maysun's cluster and find the issue is different cluster's `ps aux | grep <process>` has different behavior (may related with the PID itself), so that it can't get the correct process ID in your and Maysun's cluster, but can get it in my and Len's cluster. `pkill` and `pgrep` can tolerate this issue.

**Comment by elsony** [comment]
Closing this issue since the fix went into both 0.6.0 and master and it has been verified on 0.6.0
