### ISSUE TITLE
Hybrid: File watcher not working for remote connections, due to inability to access WebSocket endpoint 

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1367]
The [codewind-gatekeeper](https://github.com/eclipse/codewind/blob/d4d52ca990b720ebfd9929ca81744f68e550ebb6/src/gatekeeper/server.js) image appears to not properly handle the WebSocket endpoint used by the filewatcher, which causes the websocket upgrade failure in Erin's message below. See steps to reproduce in the comment below: https://github.com/eclipse/codewind/issues/1367#issuecomment-561779882

(Jonathan)

### Erin's original description:

Changes to files are not getting picked up for remote connections and the following exception gets printed out every few seconds once a new remote connection has been created:

```
org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 200 OK
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:532)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:543)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:523)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:486)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:326)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1161)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1534)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:200)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:141)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:75)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:151)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.util.concurrent.ExecutionException: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 200 OK
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
	at org.eclipse.codewind.filewatchers.core.internal.WebSocketManagerThread.establishOrReestablishConnection(WebSocketManagerThread.java:246)
	at org.eclipse.codewind.filewatchers.core.internal.WebSocketManagerThread.run(WebSocketManagerThread.java:129)
Caused by: org.eclipse.jetty.websocket.api.UpgradeException: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 200 OK
	at org.eclipse.jetty.websocket.client.WebSocketUpgradeRequest.onComplete(WebSocketUpgradeRequest.java:532)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:218)
	at org.eclipse.jetty.client.ResponseNotifier.notifyComplete(ResponseNotifier.java:210)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:543)
	at org.eclipse.jetty.client.HttpReceiver.terminateResponse(HttpReceiver.java:523)
	at org.eclipse.jetty.client.HttpReceiver.responseSuccess(HttpReceiver.java:486)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.messageComplete(HttpReceiverOverHTTP.java:326)
	at org.eclipse.jetty.http.HttpParser.parseFields(HttpParser.java:1161)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1534)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.parse(HttpReceiverOverHTTP.java:200)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:141)
	at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:75)
	at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:151)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:543)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:398)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by jopit** [comment]
Is this different from #1309 ?

**Comment by eharris369** [comment]
I thought so because there is no authentication required by PFE for the socket that file watcher is using yet according to Jonathan's latest comment in #1309: "Portal folks have not yet secured the WebSocket endpoint used by filewatchers for project notifications, so there is no need to include that in the FW PRs for this release."

**Comment by jopit** [comment]
My understanding is that FW uses both sockets @jgwest can you clarify?

**Comment by jgwest** [comment]
@jopit Nope, FW just the standard non-UI websocket, eg it doesn't use the socket.io socket for anything.

**Comment by jgwest** [comment]
I'm able to reproduce using a standalone websocket client, eg not requiring FWd with latest changes. I'm unable to establish a connection to:
```
wss://codewind-gatekeeper-k3rj1yvk.codewind-ide-7674b4bd9abbdeea0be228236d5275c9-0001.tor01.containers.appdomain.cloud/websockets/file-changes/v1
```

**Comment by malincoln** [comment]
@tobespc pls review and assign.  Thanks

**Comment by malincoln** [comment]
@tobespc this one identified as required for dcut.

**Comment by markcor11** [comment]
Made some progress,  I have this working on my test environment now and able to connect over TLS via the Codewind Gatekeeper 

![image](https://user-images.githubusercontent.com/28102564/70324931-b5700f80-1828-11ea-9a09-640e0f8dd700.png)

**Comment by malincoln** [comment]
@eharris369 pls verify and close.  Thanks

**Comment by jgwest** [comment]
I saw this as well, and was able to verify it is fixed by https://github.com/eclipse/codewind/pull/1409

**Comment by maysunfaisal** [comment]
/reopen

I still see this issue with latest cwctl and gatekeeper

### cwctl build info
```
# Build date: 2019-12-09-16:04:16
build_info.url=https://download.eclipse.org/codewind/codewind-installer/master/37
build_info.linux.SHA-1=2a18d42b4240c779ebe2019e30ed3fef13567e86
build_info.macos.SHA-1=f73c70f62ff03ea9e73aee6a27f2b48f3b7493ed
build_info.win.SHA-1=a8f458187943349d93d90f31b45e1bade83c45a6
```

### gatekeeper pod describe
```
Events:
  Type    Reason     Age   From                         Message
  ----    ------     ----  ----                         -------
  Normal  Scheduled  43m   default-scheduler            Successfully assigned codewind/codewind-gatekeeper-k3yq1t48-5d9666db9f-2gtx4 to maysun-okd-worker2
  Normal  Pulling    43m   kubelet, maysun-okd-worker2  pulling image "eclipse/codewind-gatekeeper-amd64:latest"
  Normal  Pulled     43m   kubelet, maysun-okd-worker2  Successfully pulled image "eclipse/codewind-gatekeeper-amd64:latest"
  Normal  Created    43m   kubelet, maysun-okd-worker2  Created container
  Normal  Started    43m   kubelet, maysun-okd-worker2  Started container
```

### My gatekeeper has the changes:
```
const https = require('https');   
    const pem = require('pem');                     
    const createCertificateAsync = promisify(pem.createCertificate);
    let keys = await createCertificateAsync({ selfSigned: true });
    server = https.createServer({ key: keys.serviceKey, cert: keys.certificate }, app)
                                 
    var proxy = new httpProxy.createProxyServer({secure: false, target: `wss://${pfe_host}:${pfe_port}`, ws:true});
    server.on('upgrade', function (req, socket, head) {
        console.log("Proxy: websocket connect 'upgrade'")
        proxy.ws(req, socket, head);         
    });                                              
                                                         
    server.listen(port, () => console.log(`Gatekeeper listening on port ${port}!`))
```

### Gatekeeper logs:
```
maysuns-mbp:workspace2 maysun$ k logs -f codewind-gatekeeper-k3yq1t48-5d9666db9f-2gtx4    

> gatekeeper@1.0.0 start /usr/src/app
> node server.js

Gatekeeper k3yq1t48 with route authentication and UI Socket pass-through
Gatekeeper configuration:
** PFE Service: https://172.30.177.45:9191
** SESSION_SECRET: <not-displayed>
** REALM: codewind
** CLIENT_ID: codewind-k3yq1t48
** AUTH_URL: https://codewind-keycloak-k3yq1t48.9.37.222.212.nip.io
** CLIENT_SECRET: <not-displayed>
** GATEKEEPER_HOST: CODEWIND-GATEKEEPER-K3YQ1T48.9.37.222.212.NIP.IO
** Access role : codewind-k3yq1t48
** Gatekeeper: Authentication is enabled - ENABLE_AUTH=1
Added environment route to : /api/v1/gatekeeper/environment
Gatekeeper listening on port 9096!
req.originalUrl = /api/pfe/ready
(node:19) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
req.originalUrl = /api/v1/templates?showEnabledOnly=true
req.originalUrl = /api/v1/imagepushregistry
req.originalUrl = /api/v1/registrysecrets
req.originalUrl = /api/v1/imagepushregistry
```

**Comment by maysunfaisal** [comment]
I see an error with Filewatcher

```
[December 9, 13:49:56.994] [2349.437] Received event [MODIFY] /Users/maysun/dev/workspace2/spremote123/src/main/java/application/rest/v1/Example.java
[December 9, 13:49:58.001] [2350.444] Batch change summary for 5d3d7850-1aaf-11ea-8563-697777a376f8 @ 1575917396994: [ >Example.java ]
[December 9, 13:49:58.001] [2350.444] Calling cwctl project sync with: { [project] [sync] [-p] [/Users/maysun/dev/workspace2/spremote123] [-i] [5d3d7850-1aaf-11ea-8563-697777a376f8] [-t] [1575915107212] }
[December 9, 13:49:59.076] [2351.519] ! ERROR !  Error running 'project sync' installer command panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x15579e6]

goroutine 1 [running]:
github.com/eclipse/codewind-installer/pkg/project.syncFiles.func1(0xc0000e0400, 0x33, 0x2390540, 0xc00038b1e0, 0x0, 0x0, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/project/sync.go:173 +0x8a6
path/filepath.walk(0xc0000e0400, 0x33, 0x2390540, 0xc00038b1e0, 0xc00016b180, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:358 +0x41c
path/filepath.walk(0x7ffeefbff7d4, 0x28, 0x2390540, 0xc00038b110, 0xc00016b180, 0x0, 0x70)
	/usr/local/go/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0x7ffeefbff7d4, 0x28, 0xc00016b180, 0x13, 0x13)
	/usr/local/go/src/path/filepath/path.go:404 +0x105
github.com/eclipse/codewind-installer/pkg/project.syncFiles(0x7ffeefbff7d4, 0x28, 0x7ffeefbff800, 0x24, 0xc0000e0280, 0x38, 0x16eebdc338c, 0xc00016afc0, 0x20, 0x20, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/project/sync.go:118 +0x257
github.com/eclipse/codewind-installer/pkg/project.SyncProject(0xc000380160, 0x21c31d1, 0x4)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/project/sync.go:96 +0x531
github.com/eclipse/codewind-installer/pkg/actions.ProjectSync(0xc000380160)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/project.go:46 +0x74
github.com/eclipse/codewind-installer/pkg/actions.Commands.func4(0xc000380160, 0x0, 0xc0000a07b0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:118 +0x2b
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.HandleAction(0x1fbe760, 0x225d4d0, 0xc000380160, 0xc000380160, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:514 +0xbe
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x21c3329, 0x4, 0x0, 0x0, 0xc00030a220, 0x1, 0x1, 0x22131dd, 0x42, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:171 +0x4a4
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc00033e000, 0xc00053de40, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:395 +0x877
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.startApp(0x21c4f3e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21d6a14, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:383 +0x808
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.Command.Run(0x21c4f3e, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21d6a14, 0x18, 0x0, ...)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/command.go:103 +0x8ef
github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli.(*App).Run(0xc000323dc0, 0xc0000d0000, 0x9, 0x9, 0x0, 0x0)
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/vendor/github.com/urfave/cli/app.go:265 +0x70b
github.com/eclipse/codewind-installer/pkg/actions.Commands()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/pkg/actions/commands.go:849 +0x77d3
main.main()
	/home/jenkins/agent/src/github.com/eclipse/codewind-installer/cmd/cli/main.go:26 +0x2c
```

which points to https://github.com/eclipse/codewind/issues/1411

so closing this now

/close
