### ISSUE TITLE
[odo] ODO projects fail to build. Unable to deploy application

### ISSUE THREAD

**Issue by naveenkaratekid** [eclipse/codewind#1514]
**Codewind version:0.7.0**
**OS: OKD 3.1**

**Che version:7.3.1**

**Description:**
All ODO Projects are failing to build and deploy. Getting a 
```Failed to build or deploy odo application```

**Steps to reproduce:**
1. In Che, create an ODO project
2. Let the project build.

Here are the logs

Codewind PFE
[codewindpfelog.txt](https://github.com/eclipse/codewind/files/3957930/codewindpfelog.txt)

Screenshot:
![Screen Shot 2019-12-12 at 4 33 54 PM](https://user-images.githubusercontent.com/19738071/70751008-87457080-1cfd-11ea-976a-ed370e1e799c.png)

Output logs from each project
**ODO Java**
```
Step 1 of 4:
- Creating odo component: cw-odojava
 •  Validating component  ...
 ✓  Validating component [3ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-odojava
Step 2 of 4:
- Building and deploying odo component: cw-odojava
Validation
 •  Checking component  ...
 ✓  Checking component [9ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✓  Creating component [140ms]
Pushing to component cw-odojava of type local
 •  Checking files for pushing  ...
 ✓  Checking files for pushing [112ms]
 •  Waiting for component to start  ...
 ✓  Waiting for component to start [25s]
 •  Syncing files to the component  ...
 ✓  Syncing files to the component [585ms]
 •  Building component  ...
```
```
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-odojava
 ✗  Blank source location, does the .odo directory exist?
- Failed to build and deploy odo component: cw-odojava
Failed to update odo application
```
------------------------------------------------
**ODO Python**
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-odopython
Warning: python is not fully supported by odo, and it is not guaranteed to work
 •  Validating component  ...
 ✓  Validating component [31ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-odopython
Step 2 of 4:
- Building and deploying odo component: cw-odopython
Validation
 •  Checking component  ...
 ✓  Checking component [17ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✓  Creating component [141ms]
Pushing to component cw-odopython of type local
 •  Checking files for pushing  ...
 ✓  Checking files for pushing [105ms]
 •  Waiting for component to start  ...
```
```
 ✓  Building component [2m]
 ✓  Changes successfully pushed to component
- Successfully built and deployed odo component: cw-odopython
Step 3 of 4:
- Creating url for odo component: cw-odopython
 ✗  The current directory does not represent an odo component. Use 'odo create' to create component here or switch to directory with a component
- Failed to create url for odo component: cw-odopython
```
------------------------------------------------
**ODO Perl**
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-odoperl
Warning: perl is not fully supported by odo, and it is not guaranteed to work
 •  Validating component  ...
 ✓  Validating component [24ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-odoperl
Step 2 of 4:
- Building and deploying odo component: cw-odoperl
Validation
 •  Checking component  ...
 ✓  Checking component [27ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✓  Creating component [145ms]
Pushing to component cw-odoperl of type local
 •  Checking files for pushing  ...
 ✓  Checking files for pushing [55ms]
 •  Waiting for component to start  ...
 ✓  Waiting for component to start [10s]
 •  Syncing files to the component  ...
 ✓  Syncing files to the component [425ms]
 •  Building component  ...
```
```
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-odoperl
 ✗  Blank source location, does the .odo directory exist?
- Failed to build and deploy odo component: cw-odoperl
Failed to update odo application
```

@jagraj

**Comment by jagraj** [comment]
/area iterative-dev
/priority stopship

@jingfuwang 
Can you take a look at this issue when you get a chance.?
I can not reproduce this issue on OpenShift 4.2 cluster. I can deploy ODO projects and I did not try on my OpenShift 3.11 cluster. We marked this issue as "stopship" for now. It will be nice you can reproduce this issue on your cluster and you can debug on Naveen's 3.11 cluster.

**Comment by sujeilyfonseca** [comment]
**Codewind version:** [0.7.0](https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/0.7.0/devfile.yaml)
**OS:** Red Hat Enterprise Linux 7 (64 bit)

**Che version:** 7.3.1
**Kubernetes cluster:** OKD/Openshift 3.11 

I only saw this problem once, but only with a Python project. However, I could not reproduce the problem now:

<img width="1674" alt="Screen Shot 2019-12-12 at 5 04 54 PM" src="https://user-images.githubusercontent.com/49531960/70753325-8531e080-1d02-11ea-99a7-a7dac985b138.png">

**Comment by GeekArthur** [comment]
I am using the **latest** `0.7.0` and can't reproduce the issue
![Screen Shot 2019-12-13 at 11 12 37 AM](https://user-images.githubusercontent.com/15131537/70814465-8bbf6700-1d99-11ea-9798-90d2cf0de965.png)

But from @naveenkaratekid 's PFE log, I find a line is suspicious
```
[32m[12/12/19 21:14:39 /portal/routes/projects/remoteBind.route.js] [INFO][39m Removing locally deleted files from project: odopython, ID: 66117630-1d24-11ea-a094-31023139e888 - .odo/config.yaml
```
Portal shouldn't remove odo project files at that time, so seems like it's the syncing issue results in the following failure of odo project build. From the history think Portal already fixed this https://github.com/eclipse/codewind/pull/1516 5 hours ago, so you can try the **latest** `0.7.0`, it should work.

**Comment by malincoln** [comment]
@naveenkaratekid pls confirm 1516 resolves this issue.  Thanks

**Comment by naveenkaratekid** [comment]
@malincoln Verifying now.

**Comment by naveenkaratekid** [comment]
Just re deployed the workspace both using using the ```latest``` devfile from ```master```, and using ```latest``` from ```0.7.0``` branches.
Just created three ODO projects (Python, Perl, and NodeJS).

Projects are still failing to build. Still getting error ```Failed to update odo application```

Here is the PFE logs for master branch with latest as well as 0.7.0 branch with latest:

[codewindpfelog_master_latest.txt](https://github.com/eclipse/codewind/files/3962588/codewindpfelog_master_latest.txt)
[codewindpfelog_0.7.0_latest.txt](https://github.com/eclipse/codewind/files/3962589/codewindpfelog_0.7.0_latest.txt)

**Comment by GeekArthur** [comment]
@naveenkaratekid From your log, this is the root casue
```
[32m[13/12/19 20:05:50 /portal/routes/projects/remoteBind.route.js] [INFO][39m Removing locally deleted files from project: odopythonodo, ID: f34b4700-1de3-11ea-bedc-655082b73465 - .odo/config.yaml, .odo/odo-file-index.json
```

Issue is `.odo` folder is deleted during project syncing step before triggering build on Turbine layer, so that the build is failed due to missing `.odo` folder. This is the parent issue: https://github.com/eclipse/codewind/issues/1533, you can verify once https://github.com/eclipse/codewind/issues/1533 is fixed.

**Comment by james-wallis** [comment]
@naveenkaratekid @GeekArthur https://github.com/eclipse/codewind/pull/1546 has been accepted into master which should fix this issue on 0.7.0, please retest using 0.7.0 branch and remove stop ship flag - master branch fix should land soon but will have a different implementation.

**Comment by GeekArthur** [comment]
I verified the issue was fixed on 0.7.0, so I remove the stopship label and add 0.8.0 release. I can close the issue once https://github.com/eclipse/codewind/issues/1533 is fixed in master (master has different implementation for the long-term fix).

**Comment by GeekArthur** [comment]
PR for master is not merged yet: https://github.com/eclipse/codewind/pull/1559, I can verify and close the issue once the PR is merged.

**Comment by naveenkaratekid** [comment]
@GeekArthur Im still seeing build failures on ODO projects.

PFE Log:

[codewindPFE_070_latest.txt](https://github.com/eclipse/codewind/files/3974257/codewindPFE_070_latest.txt)

Screenshot:
![image](https://user-images.githubusercontent.com/19738071/71013089-1962c580-20be-11ea-9959-50f29a8eba37.png)

**Comment by GeekArthur** [comment]
@naveenkaratekid Can you run `oc get po --selector=app=codewind-pfe -o jsonpath='{.items[*].status.containerStatuses[*].imageID}'
` to see which PFE SHA you use?

**Comment by naveenkaratekid** [comment]
@GeekArthur Here is the output I got from running the command you specified:

```docker-pullable://docker.io/eclipse/codewind-pfe-amd64@sha256:cd3b159c1145cb6f1b9b069d55bcca75aa4fe2743dedeedb39baedd21532ac45```

**Comment by GeekArthur** [comment]
@naveenkaratekid The one you use is not the latest PFE image so it doesn't include Portal's fix, 
`6ab50c345c4946208ddbcdf68a229c706b18360e6c1c9c635fe22ed88e90f53b` from https://hub.docker.com/layers/eclipse/codewind-pfe-amd64/0.7.0/images/sha256-6ab50c345c4946208ddbcdf68a229c706b18360e6c1c9c635fe22ed88e90f53b. You can try again with the latest PFE image.

**Comment by GeekArthur** [comment]
@naveenkaratekid Are you trying to verify 0.7.0 or master? Like I said master still doesn't work https://github.com/eclipse/codewind/issues/1514#issuecomment-566607347

**Comment by naveenkaratekid** [comment]
@GeekArthur I am verifying using this devfile:

```
http://che-che.9.42.17.120.nip.io/f?url=https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/latest/devfile.yaml
```

If this isn't the correct link to test on Che, could you provide me with that link?

**Comment by GeekArthur** [comment]
@naveenkaratekid You can use this one, the one you use is latest master not latest 0.7.0
```
https://raw.githubusercontent.com/eclipse/codewind-che-plugin/0.7.0/devfiles/0.7.0/devfile.yaml
```

**Comment by naveenkaratekid** [comment]
Let me verify.

**Comment by naveenkaratekid** [comment]
@GeekArthur I just verified, and I found some strange observations.

The Python ODO now builds and runs successfully. The Java ODO stays stuck at the ```Starting Build Succeeded``` stage. 
The NodeJS ODO fails off the bat when I create a project.
The Perl ODO showed ``````Starting [Build Successful]```, but then now it shows that it failed.

Screenshot:
![image](https://user-images.githubusercontent.com/19738071/71024700-859bf400-20d3-11ea-92ea-c6582ccce679.png)


PFE Log:
[codewindPFE_070.txt](https://github.com/eclipse/codewind/files/3974921/codewindPFE_070.txt)

**Comment by GeekArthur** [comment]
Your screenshot displays the nodejs project, looks like your cluster already had the odo resource with the same component name before. Can you delete all your workspaces then re-create a new one with the latest 0.7.0 and check your PVs are available. Then create odo projects again, if you still hit the issue, other than PFE log, please post the odo.build.log as well for the failed odo projects. odo.build.log located at `/codewind-workspace/.logs/<project log dir>` in PFE container, or you can copy the log directly from IDE by clicking `Show all logs` then choose `odo.build.log`

**Comment by GeekArthur** [comment]
I just created some odo projects and they build fine.

![Screen Shot 2019-12-17 at 2 38 29 PM](https://user-images.githubusercontent.com/15131537/71028283-001c4200-20db-11ea-9491-bf6129b04ad6.png)

**Comment by naveenkaratekid** [comment]
**odo.build.log for Python**
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-pythonodoodo
Warning: python is not fully supported by odo, and it is not guaranteed to work
 •  Validating component  ...
 ✓  Validating component [6ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-pythonodoodo
Step 2 of 4:
- Building and deploying odo component: cw-pythonodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [9ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✗  Creating component [38ms]
 ✗  Failed to create component with name cw-pythonodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-pythonodoodo-app" already exists
unable to create ImageStream for cw-pythonodoodo-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/occlient/occlient.go:1110
github.com/openshift/odo/pkg/component.CreateFromPath
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:243
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:419
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:cw-pythonodoodo SourcePath:./ SourceRef: SourceType:local ImageName:python EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:420
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
- Failed to build and deploy odo component: cw-pythonodoodo
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-pythonodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [13ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✗  Creating component [27ms]
 ✗  Failed to create component with name cw-pythonodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-pythonodoodo-app" already exists
unable to create ImageStream for cw-pythonodoodo-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/occlient/occlient.go:1110
github.com/openshift/odo/pkg/component.CreateFromPath
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:243
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:419
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:cw-pythonodoodo SourcePath:./ SourceRef: SourceType:local ImageName:python EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:420
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
- Failed to build and deploy odo component: cw-pythonodoodo
Failed to update odo application
```

**odo.build.log for Java**
```
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-javaodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [6ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✗  Creating component [14ms]
 ✗  Failed to create component with name cw-javaodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-javaodoodo-app" already exists
unable to create ImageStream for cw-javaodoodo-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/occlient/occlient.go:1110
github.com/openshift/odo/pkg/component.CreateFromPath
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:243
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:419
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:cw-javaodoodo SourcePath:./ SourceRef: SourceType:local ImageName:codewind-odo-openjdk18 EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP 8443/TCP 8778/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:420
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
- Failed to build and deploy odo component: cw-javaodoodo
Failed to update odo application
```

**odo.build.log for NodeJS**
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-nodejsodoodo
 •  Validating component  ...
 ✓  Validating component [4ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-nodejsodoodo
Step 2 of 4:
- Building and deploying odo component: cw-nodejsodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [11ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✓  Creating component [115ms]
Pushing to component cw-nodejsodoodo of type local
 •  Checking files for pushing  ...
 ✓  Checking files for pushing [25ms]
 •  Waiting for component to start  ...
 ✓  Waiting for component to start [9s]
 •  Syncing files to the component  ...
 ✓  Syncing files to the component [306ms]
 •  Building component  ...
 ✓  Building component [48s]
 ✓  Changes successfully pushed to component
- Successfully built and deployed odo component: cw-nodejsodoodo
Step 3 of 4:
- Creating url for odo component: cw-nodejsodoodo
 ✓  URL cw-nodejsodoodo created for component: cw-nodejsodoodo
To create URL on the OpenShift Cluster, please use `odo push`
- Successfully created url for odo component: cw-nodejsodoodo
Step 4 of 4:
- Building and deploying odo component: cw-nodejsodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [35ms]
Configuration changes
 •  Retrieving component data  ...
 ✓  Retrieving component data [24ms]
 •  Applying configuration  ...
 ✓  Applying configuration [21ms]
Applying URL changes
 ✓  URL cw-nodejsodoodo: http://cw-nodejsodoodo-app-che.9.42.17.120.nip.io created
Pushing to component cw-nodejsodoodo of type local
 •  Checking file changes for pushing  ...
 ✓  Checking file changes for pushing [26ms]
 •  Waiting for component to start  ...
 ✓  Waiting for component to start [8ms]
 •  Syncing files to the component  ...
 ✓  Syncing files to the component [169ms]
 •  Building component  ...
 ✓  Building component [27s]
 ✓  Changes successfully pushed to component
- Successfully built and deployed odo component: cw-nodejsodoodo
Successfully created, built and deployed odo application
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-nodejsodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [46ms]
Configuration changes
 •  Retrieving component data  ...
 ✓  Retrieving component data [26ms]
 •  Applying configuration  ...
 ✓  Applying configuration [24ms]
Applying URL changes
 ✓  URL cw-nodejsodoodo already exists
Pushing to component cw-nodejsodoodo of type local
 •  Checking file changes for pushing  ...
 ✓  Checking file changes for pushing [17ms]
 ✓  No file changes detected, skipping build. Use the '-f' flag to force the build.
- Successfully built and deployed odo component: cw-nodejsodoodo
Successfully updated odo application
```

**odo.build.log for Perl**
```
Creating, building and deploying odo application
Step 1 of 4:
- Creating odo component: cw-perlodoodo
Warning: perl is not fully supported by odo, and it is not guaranteed to work
 •  Validating component  ...
 ✓  Validating component [9ms]
Please use `odo push` command to create the component with source deployed
- Successfully created odo component: cw-perlodoodo
Step 2 of 4:
- Building and deploying odo component: cw-perlodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [12ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✗  Creating component [36ms]
 ✗  Failed to create component with name cw-perlodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-perlodoodo-app" already exists
unable to create ImageStream for cw-perlodoodo-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/occlient/occlient.go:1110
github.com/openshift/odo/pkg/component.CreateFromPath
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:243
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:419
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:cw-perlodoodo SourcePath:./ SourceRef: SourceType:local ImageName:perl EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:420
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
- Failed to build and deploy odo component: cw-perlodoodo
Updating odo application
Step 1 of 1:
- Building and deploying odo component: cw-perlodoodo
Validation
 •  Checking component  ...
 ✓  Checking component [15ms]
Configuration changes
 ✓  Initializing component
 •  Creating component  ...
 ✗  Creating component [27ms]
 ✗  Failed to create component with name cw-perlodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-perlodoodo-app" already exists
unable to create ImageStream for cw-perlodoodo-app
github.com/openshift/odo/pkg/occlient.(*Client).BootstrapSupervisoredS2I
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/occlient/occlient.go:1110
github.com/openshift/odo/pkg/component.CreateFromPath
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:243
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:419
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
failed to create component with args {Name:cw-perlodoodo SourcePath:./ SourceRef: SourceType:local ImageName:perl EnvVars:[DEBUG_PORT=5858] Ports:[8080/TCP] Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},} ApplicationName:app Wait:false StorageToBeMounted:map[] StdOut:<nil>}
github.com/openshift/odo/pkg/component.CreateComponent
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component.go:420
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).createCmpIfNotExistsAndApplyCmpConfig
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:72
github.com/openshift/odo/pkg/odo/cli/component.(*CommonPushOptions).Push
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/common_push.go:145
github.com/openshift/odo/pkg/odo/cli/component.(*PushOptions).Run
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:105
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:28
github.com/openshift/odo/pkg/odo/cli/component.NewCmdPush.func1
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/push.go:120
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:702
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:783
github.com/openshift/odo/vendor/github.com/spf13/cobra.(*Command).Execute
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:736
main.main
	/builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:72
runtime.main
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/proc.go:200
runtime.goexit
	/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-1.12-golang/src/runtime/asm_amd64.s:1337
- Failed to build and deploy odo component: cw-perlodoodo
Failed to update odo application
```

**Comment by GeekArthur** [comment]
Yeah, from the logs, we can clearly see for all the failed builds, they have the same type of error like this: `Failed to create component with name cw-perlodoodo. Please use `odo config view` to view settings used to create component. Error: imagestreams.image.openshift.io "cw-perlodoodo-app" already exists
unable to create ImageStream for cw-perlodoodo-app`

That means you already had ImageStream with the same component name (I am not sure why your cluster had that, may from test automation, may from manual tests), you have to delete your workspace and ensure no existing ImageStream then try again.

**Comment by naveenkaratekid** [comment]
If I delete the workspace, how do I verify that the ImageStream doesn't exist?

Do I need to delete the che workspace?

**Comment by GeekArthur** [comment]
> If I delete the workspace, how do I verify that the ImageStream doesn't exist?
You can run `kubectl get is`

> Do I need to delete the che workspace and re-deploy it?
Yes, you need delete Che **workspace** (not delete Che) and use devfile to re-deploy it as before

**Comment by naveenkaratekid** [comment]
Here is the output of ```kubectl get is```

```NAME                     DOCKER REPO                                                   TAGS      UPDATED
codewind-odo-openjdk18   docker-registry.default.svc:5000/che/codewind-odo-openjdk18   latest    4 days ago
cw-javaodoodo-app        docker-registry.default.svc:5000/che/cw-javaodoodo-app                  
cw-nodejsodoodo-app      docker-registry.default.svc:5000/che/cw-nodejsodoodo-app                
cw-odo-perl-app          docker-registry.default.svc:5000/che/cw-odo-perl-app                    
cw-odo-py-app            docker-registry.default.svc:5000/che/cw-odo-py-app                      
cw-odo-python-app        docker-registry.default.svc:5000/che/cw-odo-python-app                  
cw-odojava-app           docker-registry.default.svc:5000/che/cw-odojava-app                     
cw-odojavaodo-app        docker-registry.default.svc:5000/che/cw-odojavaodo-app                  
cw-odonodejs-app         docker-registry.default.svc:5000/che/cw-odonodejs-app                   
cw-odonodejsodo-app      docker-registry.default.svc:5000/che/cw-odonodejsodo-app                
cw-odoperl-app           docker-registry.default.svc:5000/che/cw-odoperl-app                     
cw-odoperlodo-app        docker-registry.default.svc:5000/che/cw-odoperlodo-app                  
cw-odoperlperl-app       docker-registry.default.svc:5000/che/cw-odoperlperl-app                 
cw-odopython-app         docker-registry.default.svc:5000/che/cw-odopython-app                   
cw-odopythonodo-app      docker-registry.default.svc:5000/che/cw-odopythonodo-app                
cw-odopythonodoodo-app   docker-registry.default.svc:5000/che/cw-odopythonodoodo-app             
cw-perlodoodo-app        docker-registry.default.svc:5000/che/cw-perlodoodo-app                  
cw-perlodoodoodo-app     docker-registry.default.svc:5000/che/cw-perlodoodoodo-app               
cw-pythonodo-app         docker-registry.default.svc:5000/che/cw-pythonodo-app                   
cw-pythonodoodo-app      docker-registry.default.svc:5000/che/cw-pythonodoodo-app                
cw-pythonodoodoodo-app   docker-registry.default.svc:5000/che/cw-pythonodoodoodo-app   

```

**Comment by GeekArthur** [comment]
You need to manually all of them except `codewind-odo-openjdk18`

**Comment by GeekArthur** [comment]
The best way for cleaning up your cluster is to delete all existing workspaces then run: 
- `kubectl get is` to check dangling image streams
- `kubectl get pvc` to check dangling PVCs
- `kubectl get pv` to check if all PVs are available

**Comment by naveenkaratekid** [comment]
When I ran the ```kubectl get pv```, I noticed that in ``che-data```, the CLAIM section says che/cw-nodejsodoodo-app-s2idata. Do I need to remove that?

```che-data         1Gi        RWO            Recycle          Released    che/cw-nodejsodoodo-app-s2idata                            131d```

**Comment by GeekArthur** [comment]
You can leave it as it is since recycler pod can handle that, but you need to make sure all workspaces are deleted then re-deploy new workspace.

**Comment by jagraj** [comment]
@GeekArthur 
Looks like Naveen has to follow all those steps apart from the fix we delivered. Is it possible our users will get into similar issue and it makes sense to doc this to clean up their environment.?

**Comment by GeekArthur** [comment]
@jagraj User won't hit this issue if user only uses Codewind for development purpose since either delete workspace or delete odo project can delete corresponding image stream automatically. But that's good point, we can doc this in case user uses the cluster for other purpose. I can drop a PR quickly to doc this issue.

**Comment by GeekArthur** [comment]
PR for documentation: https://github.com/eclipse/codewind-docs/pull/273

**Comment by GeekArthur** [comment]
PR for doc has been merged, close the issue.
