### ISSUE TITLE
Can't restart Codewind node project in debug mode

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#1709]
Using a newly created Codewind node project (not Appsody) when I try to restart it in debug mode I get an error dialog popping up with the message: projectStatusController.appStatusContainerStopped.  This is coming from a projectStatusChanged event:

```
[10/01/20 19:35:05 node1] [INFO] Emitting event 
 message: projectStatusChanged
 data: {
  "projectID": "c6165f60-33df-11ea-a2a1-998725219ae8",
  "appStatus": "stopped",
  "appErrorStatus": "projectStatusController.appStatusContainerStopped",
  "detailedAppStatus": {
    "severity": "ERROR",
    "message": "projectStatusController.appStatusContainerStopped",
    "notify": true
  }
}
```

I am using the latest 0.8.0 Codewind and Eclipse IDE.  I tried both on Windows and MAC with the same results.

Full log file: 
[pfelog.txt](https://github.com/eclipse/codewind/files/4047618/pfelog.txt)

**Comment by tetchel** [comment]
I see it too

```
[10/01/20 19:34:54 nodeproj] [ERROR] runScript : 1105 | + set +x

[10/01/20 19:34:54 nodeproj] [ERROR] runScript : 1105 | + nodemon --exec npm run debug

[10/01/20 19:34:54 nodeproj] [INFO] Project start for restart was successful
[10/01/20 19:34:54 User.js] [INFO] Updating status for project fe9913f0-33df-11ea-8330-65459ad4e4f2.
[10/01/20 19:34:54 nodeproj] [INFO] Application state changed for project: fe9913f0-33df-11ea-8330-65459ad4e4f2 from: stopped, to: starting
[10/01/20 19:34:54 nodeproj] [INFO] Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "fe9913f0-33df-11ea-8330-65459ad4e4f2",
  "appStatus": "starting"
}
[10/01/20 19:34:54 nodeproj] [INFO] Internal port: 3000
[10/01/20 19:34:54 nodeproj] [INFO] Internal debug port: 9229
[10/01/20 19:34:54 nodeproj] [INFO] Exposed port: 32816
[10/01/20 19:34:54 nodeproj] [INFO] Exposed debug port: 32815
[10/01/20 19:34:54 nodeproj] [INFO] All the exposed container ports: ["3000","9229"]
[10/01/20 19:34:54 nodeproj] [INFO] All the host ports: ["32816","32815"]
[10/01/20 19:34:54 nodeproj] [INFO] Emitting event
 message: projectRestartResult
 data: {
  "operationId": "f6a93019625b3e7a3c2e4e86c9946816",
  "projectID": "fe9913f0-33df-11ea-8330-65459ad4e4f2",
  "status": "success",
  "startMode": "debugNoInit",
  "ports": {
    "exposedPort": "32816",
    "internalPort": "3000",
    "exposedDebugPort": "32815",
    "internalDebugPort": "9229"
  },
  "containerId": "9dc9572f8e9c1ea1f171b87d32c577ec4e3f94f63d75eced46d12b70ddceb3f0"
}
[10/01/20 19:35:06 nodeproj] [ERROR] getContainerStatus : 167 | | The command docker exec,cw-nodeproj-fe9913f0-33df-11ea-8330-65459ad4e4f2,/scripts/noderun.sh,isActive failed with exit code 1
[10/01/20 19:35:06 nodeproj] [INFO] pingInTransitApplications: Application state for project fe9913f0-33df-11ea-8330-65459ad4e4f2 has changed from starting to stopped
[10/01/20 19:35:06 nodeproj] [INFO] Emitting event
 message: projectStatusChanged
 data: {
  "projectID": "fe9913f0-33df-11ea-8330-65459ad4e4f2",
  "appStatus": "stopped",
  "appErrorStatus": "projectStatusController.appStatusContainerStopped",
  "detailedAppStatus": {
    "severity": "ERROR",
    "message": "projectStatusController.appStatusContainerStopped",
    "notify": true
  }
}
```

**Comment by tetchel** [comment]
I reported the bad detailed status here, https://github.com/eclipse/codewind/issues/1697 it looks like it was fixed in master

**Comment by rajivnathan** [comment]
It's now in 0.8.0 as well: https://github.com/eclipse/codewind/pull/1704

Can you please try again?

**Comment by eharris369** [comment]
The message is cleaned up now but it still won't start in debug mode.

![image](https://user-images.githubusercontent.com/9484320/72261095-323d9880-35e2-11ea-98b6-b4f1d1b76172.png)

The app.log has the following at the end:

+ nodemon@2.0.2
updated 1 package in 3.999s
[33m[nodemon] 2.0.2[39m
[33m[nodemon] to restart at any time, enter `rs`[39m
[33m[nodemon] watching dir(s): *.*[39m
[33m[nodemon] watching extensions: js,mjs,json[39m
[32m[nodemon] starting `npm run debug`[39m
npm ERR! missing script: debug

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-10T08_51_54_664Z-debug.log
[31m[nodemon] app crashed - waiting for file changes before starting...[39m

**Comment by tetchel** [comment]
There is no more `debug` script in our node template since late october [commit](https://github.com/codewind-resources/nodeExpressTemplate/commit/4f934e4ced9957d4a33e6692ca1ae19c065817cb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2). Is it possible this has been broken since then? 😖

**Comment by tobespc** [comment]
will fix the template asap

**Comment by eharris369** [comment]
This is working now.

**Comment by rwalle61** [comment]
I get this problem on latest master if I call `POST /projects/:id/restart` with startMode `debug` on a Node.js project:
```
[31/01/20 12:32:11 server.js] [DEBUG] POST /api/v1/projects/b3f02540-4425-11ea-86a6-e9bbc9452db4/restart called
[31/01/20 12:32:11 User.js] [DEBUG] Restarting project [object Object] (startMode: debug)
[31/01/20 12:32:42 Turbine] [ERROR] [File Name: /file-watcher/server/dist/controllers/projectsController.js | Function Name: projectAction | Line Number: 972] An error occurred while executing projectAction:
 {"action":"restart","projectID":"b3f02540-4425-11ea-86a6-e9bbc9452db4","startMode":"debug"}
 400: Node.js projects do not support restarting in debug mode.
[31/01/20 12:32:42 /portal/modules/FileWatcher.js] [DEBUG] Received filewatcher module response: { statusCode: 400,
  status: 'failed',
  error:
   { msg: 'Node.js projects do not support restarting in debug mode.' } }
[31/01/20 12:32:42 /portal/routes/projects/restart.route.js] [ERROR] { FilewatcherError: Request error for project b3f02540-4425-11ea-86a6-e9bbc9452db4.
Node.js projects do not support restarting in debug mode.
    at handleProjectActionResponse (/portal/modules/FileWatcher.js:56:727)
    at FileWatcher.performProjectActionRequest (/portal/modules/FileWatcher.js:23:5379)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'FilewatcherError',
  code: 'REQUEST_VALIDATION_ERROR',
  info:
   { name: 'FilewatcherError',
     code: 'REQUEST_VALIDATION_ERROR',
     message:
      'Request error for project b3f02540-4425-11ea-86a6-e9bbc9452db4. Node.js projects do not support restarting in debug mode.' } }
```

**Comment by tetchel** [comment]
You will get this error if the project was created between when the template was broken in October and fixed above, does it happen with a new project too?

**Comment by rwalle61** [comment]
this happens with a project created from the fixed template, I think because the cause may be the Node.js project capabitilites in nodejsProject.ts. 

Let's move discussion of the behaviour of the PFE API to https://github.com/eclipse/codewind/issues/1968 and keep this issue for tracking the ability to restart a project in either debug mode in the IDEs, which has been resolved
