### ISSUE TITLE
cwctl error when removing project: Project unbind failed with status code Ê

### ISSUE THREAD

**Issue by eharris369** [eclipse/codewind#2193]
When I try to remove a project using cwctl it does get removed but the return code for the command is 1 and it gives an error message.  Because of this an error dialog shows in the IDE.  I am on Windows 10 and downloaded the latest cwctl master build.
```
C:\Users\ERINHarris\.codewind\latest>cwctl project remove --id fa1fd220-4a2b-11ea-b43a-79a1085e79fe
time="2020-02-13T11:21:34-05:00" level=error msg="{\"error\":\"proj_unbind\",\"error_description\":\"Project unbind failed with status code Ê\"}"

C:\Users\ERINHarris\.codewind\latest>echo %errorLevel%
1
```

Also when the --json option is used the error message is nested in one level which the IDE can't parse:

```
{"error":"proj_unbind","error_description":"{\"error\":\"proj_unbind\",\"error_description\":\"Project unbind failed with status code Ê\"}"}
```

**Comment by eharris369** [comment]
I could not reproduce this with 0.9.0 - just latest.

**Comment by jopit** [comment]
This issue will be stop-ship for 0.10.0 (not marking it as such yet since 0.9.0 isn't quite done)...

**Comment by jopit** [comment]
A fix for this would be appreciated -- it's getting really annoying when developing IDE code because when you try to remove multiple projects at once, the IDE removal logic bails out on the first error.

**Comment by malincoln** [comment]
@tobespc pls assign. Thanks

**Comment by eharris369** [comment]
This also affects other things like drag and drop of a project from one connection to another in the Eclipse IDE.

**Comment by tobespc** [comment]
This will be picked up today

**Comment by hhellyer** [comment]
I've pushed a fix under https://github.com/eclipse/codewind-installer/pull/391 it's awaiting review.

**Comment by malincoln** [comment]
@eharris369 pls verify and close. Thanks

**Comment by eharris369** [comment]
I installed 0.10.0 this morning and am still seeing an error (slightly different message):
![image](https://user-images.githubusercontent.com/9484320/75986485-27093980-5ebc-11ea-98ed-ca43013d887e.png)

**Comment by jopit** [comment]
Moving this back out of verify as it's still not working.

**Comment by jopit** [comment]
Note that removing a project in VSCode does not run into this error because the VSCode extension is still calling the REST API for removing projects.

**Comment by tetchel** [comment]
yeah, and 202 is a success status code. probably we're checking for 200 specifically, instead of any 'success' code.

**Comment by malincoln** [comment]
> Moving this back out of verify as it's still not working.

@hhellyer ^^^

**Comment by james-wallis** [comment]
/assign

The API docs say that we return a `202` on successful deletion (as @tetchel says) but in the CLI we're checking for a `200`.

Running the command locally produces: 
```
cwctl project remove --id 2a188730-61ef-11ea-985f-957c13cc68ba

ERRO[0000] Project unbind failed with status code 202
exit status 1
```

**Comment by james-wallis** [comment]
PR raised here: https://github.com/eclipse/codewind-installer/pull/400
I've verified locally that I can run `cwctl project remove` and no longer see the failure.

**Comment by malincoln** [comment]
@eharris369 updated fix merged.  Pls verify and close. Thanks

**Comment by eharris369** [comment]
It is fixed in master but not 0.10.0. I don't see a PR for 0.10.0, just master.

**Comment by james-wallis** [comment]
@eharris369 the PR for 0.10.0 has been merged

**Comment by eharris369** [comment]
Verified that this is fixed in master and 0.10.0.
