### ISSUE TITLE
API Test failed in Codewind build  -  exec: "dbus-launch": executable file not found in $PATH. 

### ISSUE THREAD

**Issue by josephca** [eclipse/codewind#2467]
**Codewind version:**
**OS:**

**Che version:**
**IDE extension version:**
**IDE version:**
**Kubernetes cluster:**

**Description:**
The API test failure causes Codewind Jenkins build failed and also affects other PR builds. 

Build log: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/621/consoleFull

09:36:59  Creating codewind-workspace
09:36:59  PFE Image: e1878fa87510
09:36:59  
09:36:59  
09:36:59  [0;36mRunning 'start.sh' to start codewind. [0m
09:36:59  
09:36:59  
09:36:59  [0;36mCREATING CODEWIND-WORKSPACE IF IT DOESN'T EXIST[0m
09:36:59  
09:36:59  [0;32mDownloading cwctl to start Codewind containers [0m
09:36:59  [1;33mSet CW_CLI_BRANCH={branch} to override the branch used to pull cwctl [0m
09:36:59  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master/start.sh: 41: [: Linux: unexpected operator
09:36:59  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master/start.sh: 49: [: x86_64: unexpected operator
09:36:59  Else condition hit, only downloading Linux CWCTL
09:36:59  
09:36:59  Downloading latest Codewind CLI built from master for platforms: linux
09:36:59  Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/build_info.properties
09:36:59  Latest cli master build is https://download.eclipse.org/codewind/codewind-installer/master/60
09:36:59  Downloading https://download.eclipse.org/codewind/codewind-installer/master/latest/cwctl-linux
09:38:38  renamed 'cwctl-linux' -> 'linux/cwctl'
09:38:38  Successfully pulled Codewind CLI for linux
09:38:38  /home/genie.codewind/jenkins-agent/workspace/Codewind_codewind_master
09:38:38  Setting image tag to test
09:38:38  
09:38:38  
09:38:38  [0;36mREMOVING EXISTING CODEWIND DOCKER CONTAINERS [0m
09:38:38  System architecture is:  amd64
09:38:38  Host operating system is:  linux
09:38:38  Please wait while containers shutdown...  
09:38:38  Top level object in '/home/genie.codewind/.codewind/docker-compose.yaml' needs to be an object not '<class 'NoneType'>'.
09:38:38  time="2020-03-12T13:38:29Z" level=error msg="exit status 1"
09:38:38  
09:38:38  
09:38:38  [0;36mSTARTING CODEWIND DOCKER CONTAINERS [0m
09:38:38  Debug: true
09:38:38  2020/03/12 13:38:29 WRITE_FILE_ERROR[204]: **exec: "dbus-launch": executable file not found in $PATH.** 
09:38:38  
09:38:38  
09:38:38  [0;31mFAILED TO START CONTAINERS [0m
09:38:38  Error starting Codewind
**Steps to reproduce:**

**Workaround:**

**Comment by james-wallis** [comment]
I took a look into this and it seems that the failure comes from within `start.sh`:
```
printf "\n\n${BLUE}STARTING CODEWIND DOCKER CONTAINERS $RESET\n";
$CWCTL $LOG_OPTION start --debug $IMAGE_TAG // Think this is the line that fails it
if [ $? -eq 0 ]; then
  printf "\n\n${GREEN}SUCCESSFULLY STARTED CONTAINERS $RESET\n";
  printf "\nCurrent running codewind containers\n";
  docker ps --filter name=codewind
else
  printf "\n\n${RED}FAILED TO START CONTAINERS $RESET\n";
  exit 1;
fi
```

So I think the `cwctl start` command has started to fail in Jenkins where we're writing to a file?

Ran `master` branch locally and it starts fine.

**Comment by josephca** [comment]
> So I think the `cwctl start` command has started to fail in Jenkins where we're writing to a file?
It might be related to another issue that I raised against Eclipse team - a recently found an issue with Jenkins build workspace location under '/home/root/workspace' instead of non-root user workspace location. 
https://github.com/eclipse/codewind/issues/2458

**Comment by jgwest** [comment]
`dbus-launch` is only available on full desktop installs of Linux (GUI, either directly or through VNC), rather than the minimal server install (no GUI, SSH access only). For example, for Ubuntu, this is the difference between the 'Ubuntu 18.04 Desktop image' and the 'Ubuntu 18.04 Server install image', but similar distinctions exist in other distributions.

In general, I don't think we can rely on the presence of this utility for starting codewind (either directly, or through our cwctl dependencies).

**Comment by maysunfaisal** [comment]
/priority stopship
/area portal

This has been happening since yesterday. Cannot `cwctl start` in docker-compose because dbus-launch is missing in PATH.

if we fix it with installing dbus-x11, we then get
```
STARTING CODEWIND DOCKER CONTAINERS 
Debug: true
2020/03/12 11:52:35 WRITE_FILE_ERROR[204]: failed to unlock correct collection '/org/freedesktop/secrets/collection/login'. 
```

Basically need to do https://github.com/eclipse/codewind/issues/2224#issuecomment-586440910 to workaround and fix it

Should this PR https://github.com/eclipse/codewind-installer/pull/405 fix it? Stopship until then.

/area portal
/priority stopship

**Comment by tetchel** [comment]
`cwctl start` is for local and shouldn't need to access the keyring anyway 🤔

**Comment by hhellyer** [comment]
We do now use the keyring locally to store docker login credentials so we can persist them across PFE restarts.
The insecure keyring changes in eclipse/codewind-installer#405 should resolve this but I don't know if that PR has been updated since the credentials persistence was added.

**Comment by jgwest** [comment]
I `git bisect`ed the cwctl repo, and this is the first commit to introduce the problem: 
https://github.com/eclipse/codewind-installer/commit/59ab994f8e7e8a57ab1a0c9d995d615d6b1d06ca

with the actual `dbus-launch` command coming from this line of this dependency:
https://github.com/godbus/dbus/blob/8e900ab0295c2569ce43c79276e714f1d84e543a/conn_other.go#L20

eg cwctl -> go-keyring -> godbus

**Comment by jgwest** [comment]
I pulled the https://github.com/eclipse/codewind-installer/pull/405 and rebuilt cwcli use that code, and the issue is still reproducible.

**Comment by hhellyer** [comment]
You need to enable the insecure keyring explicitly. We've pulled the changes to store the docker credentials *until* the insecure keyring is available. Once that is in we will need to modify the `cwctl start` command in the build so that it starts up using the insecure keyring.

With the changes reverted from cwctl the latest codewind master build (625) is green: https://ci.eclipse.org/codewind/job/Codewind/job/codewind/job/master/

**Comment by malincoln** [comment]
both fixes should be tested and merged by UK EOD today.

**Comment by malincoln** [comment]
@josephca @maysunfaisal just confirming this can be fixed in the next release?

**Comment by malincoln** [comment]
problem not in 0.10.0 code based.

**Comment by hhellyer** [comment]
Further to this the problem is not in 0.10.0 *but* it does exist in the 0.10.0 builds as the Jenkinsfile always pulls the latest master build of cwctl.

As this will block the merging of PR's for stop ship defects we have merged the same fix in under https://github.com/eclipse/codewind/pull/2522

Long term it would probably be better to use the matching build of cwctl, the Jenkins build contains the right env vars that we can work out what branch we are targetting and I have raised https://github.com/eclipse/codewind/issues/2523 so that we can fix this properly once we have a bit more time.

**Comment by hhellyer** [comment]
Both master and 0.10.0 branches are now passing. https://github.com/eclipse/codewind/issues/2523 will resolve future issues with a codewind branches not being forward compatible with changes to cwctl. I think this issue can be verified and closed.

**Comment by josephca** [comment]
Both master and 0.10.0 builds are running fine. Closing the issue.
