### ISSUE TITLE
docker.io secret doesn't work after restarting local PFE

### ISSUE THREAD

**Issue by tetchel** [eclipse/codewind#2588]
**Codewind version:** master
**OS:** any

**Description:**
docker.io secret doesn't work after restarting local PFE

**Steps to reproduce:**
On the **local** connection:
1. Add a registry secret with address `docker.io`. Note it gets added as `index.docker.io/v1/`. The address in `<pfe>/.docker/config.json` is `index.docker.io/v1/` too. I know that @maysunfaisal implemented it this way because `index.docker.io/v1/` is required on local for some reason (`docker.io` doesn't work)
2. The secret should work.
3. Restart PFE
4. If you open the image registry manager, or inspect `<pfe>/.docker/config.json`, the address is now `docker.io`. 
5. The registry now doesn't work, and https://github.com/eclipse/codewind/issues/2540 is hit when you try and delete it, so you can't even recreate the secret.

**Workaround:** 

Stop PFE, manually delete `org.eclipse.codewind.local` from the keychain, restart PFE, and go back to step 1.

**Comment by tetchel** [comment]
I think this should be stopship because it breaks the core use-case of the new local docker login functionality

**Comment by tetchel** [comment]
Also, if I enter `docker.io/` instead of `docker.io` as the address, it doesn't get "translated" to `index.docker.io/v1/`. I think the trailing `/` should be ignored

**Comment by hhellyer** [comment]
Looks like the issue with the trailing `/` is actually in the registry code in PFE: https://github.com/eclipse/codewind/blob/2851d547e75a93a6f1c55eafa06bc609b21ad64d/src/pfe/portal/modules/User.js#L939

@maysunfaisal - Can this be fixed by just checking for the trailing `/` or are there other ways the user could enter docker.io registries that would also break?

**Comment by tetchel** [comment]
Fixed in master

**Comment by tetchel** [comment]
On 0.11.0, though, it looks like the trailing slash issue is still present

![image](https://user-images.githubusercontent.com/8888438/78813692-67684580-799b-11ea-8a9a-df7658adbb6f.png)

**Comment by tetchel** [comment]
well, 0.11 is released and it works in master so I suppose this is as fixed as it's going to get :)
