### ISSUE TITLE
SVT: [Remote] There is a problem with the remote/hybrid scenarios where the first load test can present a status stuck in "Requested"

### ISSUE THREAD

**Issue by sujeilyfonseca** [eclipse/codewind#2656]
**Codewind version:** 0.11.0
**OS:** VM with Windows 10 (w. OKD/Openshift cluster)

**IDE extension version:** 0.11.0
**IDE version:** Code 1.43.2

**Description:** There is a problem with the remote/hybrid scenarios where the first load test can present a status stuck in "Requested". However, after waiting for a while, a refresh will make the user see the test results.

<img width="1674" alt="Screen Shot 2020-04-09 at 2 19 52 PM" src="https://user-images.githubusercontent.com/49531960/78927621-35271880-7a6d-11ea-8d37-2d75061a2566.png">

![remote-refresh](https://user-images.githubusercontent.com/49531960/78926745-9c43cd80-7a6b-11ea-88db-908c9bfa9326.gif)

**Workaround:** 
Refresh the browser after seeing the load test stuck in "Requested" for a long time.

**Note:** The issue came after investigating https://github.com/eclipse/codewind/issues/2284.

@jagraj

**Comment by stalleyj** [comment]
This should be fixed now, please retest.

**Comment by sujeilyfonseca** [comment]
Hey @stalleyj, thank you for updating the issue. However, I still see the same behavior with the latest Codewind:

```
# Build date: 2020-04-23-11:09:42
build_info.url=https://download.eclipse.org/codewind/codewind-vscode/master/90
build_info.che.SHA-1=0a7b770c708c597c1383944e888fb0425744e76e
build_info.SHA-1=748cc82853c9c81e70f714d205ec84bd3f522ea7
```
<img width="1657" alt="Screen Shot 2020-04-23 at 11 37 22 AM" src="https://user-images.githubusercontent.com/49531960/80119992-679a4080-8558-11ea-8f13-b55166650e31.png">

<img width="1655" alt="Screen Shot 2020-04-23 at 11 48 24 AM" src="https://user-images.githubusercontent.com/49531960/80120001-69640400-8558-11ea-8daf-1d44c3bfdd38.png">


[remote-codewind-pfe.txt](https://github.com/eclipse/codewind/files/4523629/remote-codewind-pfe.txt)
[remote-codewind-performance.txt](https://github.com/eclipse/codewind/files/4523630/remote-codewind-performance.txt)
[microprofile-load-test_trimmed-video.mov.zip](https://github.com/eclipse/codewind/files/4523646/microprofile-load-test_trimmed-video.mov.zip)

**Comment by tobespc** [comment]
I cannot recreate this on 0.12 or master running in local or remote

**Comment by sujeilyfonseca** [comment]
I can still reproduce this problem with the latest Codewind 0.12.0, but I'll proceed to close this issue since we have another one to track this problem: https://github.com/eclipse/codewind/issues/2901
