### ISSUE TITLE
SVT : Eclipse IDE on Linux, projects intermittently fail to delete

### ISSUE THREAD

**Issue by mmulholl** [eclipse/codewind#469]
**Codewind version:**   Codewind tech preview	0.4.0.v201909161757	
**OS:** Linux

**Che version:**
**IDE extension version:**
**IDE version:** Eclipse IDE for Eclipse Committers Version: 2019-06 (4.12.0)
**Kubernetes cluster:**

**Description:**
Projects intermittently fail to remove from disk. Running my automated test on Linux I get occasional failures to remove a project from disk. In the test I create one each of the base codewind project types and always one or two fail to delete. Open Liberty, Node, Lagom, Spring project have all failed, but generally pass.  

Have not tested windows or mac yet

**Steps to reproduce:**

**Workaround:**

**Comment by jgwest** [comment]
Slightly similar Windows-only bug in Codewind Eclipse, which was recently fixed, but this fix should be in the driver you are testing with, based on the dates: https://github.com/eclipse/codewind-eclipse/issues/245

**Comment by eharris369** [comment]
It looks like there are two issues here:

- Maven projects can fail to delete because there are Maven jobs running in Eclipse that are holding on to the files.  Not sure how to get around this one except to wait for all existing jobs to be complete before trying to delete.  Also not sure what happens if Maven tries to start another job in the middle of the delete - hopefully Eclipse removes the project first and notifies any listeners before it tries to remove the contents.
- A timing issue where a project stops showing in the project listing before the project delete event is received.  Would need to keep a separate map of project id to Eclipse project to get around this one.

**Comment by eharris369** [comment]
The second issue (timing issue between project listing and delete event) is fixed through PR: https://github.com/eclipse/codewind-eclipse/pull/302
For the first issue I cannot find that m2e is using a family for its jobs.  It does appear to set this scheduling rule for most jobs but doing the same thing for my delete job did not help:
```
job.setRule(ResourcesPlugin.getWorkspace().getRuleFactory().buildRule());
```
Nor did setting the rule to the project being deleted or the workspace root work.

**Comment by mmulholl** [comment]
@eharris369 I am still seeing the happen in the latest driver, but maybe with less regularity:
Codewind tech preview	0.4.0.v201909191538

**Comment by mmulholl** [comment]
seeing delete failures on all platforms, linux, windows and mac

**Comment by jgwest** [comment]
@eharris369 Re: the second issue, could you keep trying to delete the project every X seconds, until it succeeds? 
```java
while(true) {
   recursiveDelete(path);
  if(recursiveFileList(path).length() > 0) {
       break;
   } else {
       Thread.sleep(2 * 1000);
   }
}
```

**Comment by eharris369** [comment]
@jgwest 
Did you mean the first issue with Maven (the second issue is fixed)?  I would be worried about doing that for 2 reasons:
    1. Trying to delete things while m2e is running might cause m2e to pop up error dialogs
    2. I am not sure how the delete is handled for projects - if it send events for files as it deletes them m2e might start other jobs

The best thing would be to know when all the m2e jobs are complete before trying to delete.  I am planning to try waiting on the following but I haven't had a chance yet:
    Job.getJobManager().isIdle()
And when idle start a job to delete that blocks the project.

**Comment by jgwest** [comment]
Yes, sorry, meant the first 😑... hmm, good thinking re: M2E popping up error dialogs, that definitely sounds possible/likely. 

`isIdle()` looks best... as food for thought, another option would be to grab the job list and look for m2e jobs, but this is kinda hacky/slighty prone to race conditions/might not be easy to identify which jobs are m2e's:
```
IJobManager jobManager = Job.getJobManager();
Job[] jobs = jobManager.find(null); 
```

(@eharris369)

**Comment by eharris369** [comment]
@jgwest I already checked if there was some way to identify m2e jobs and I could not find one.  They don't appear to have their own job family or anything easy to search on like that.  I suppose I could look at the class name but I don't think that is a good idea.  So I posted a question on stack overflow but nobody has answered yet: https://stackoverflow.com/questions/58016123/need-an-eclipse-scheduling-rule-so-my-project-delete-waits-for-all-m2e-jobs-to-f.

**Comment by jgwest** [comment]
@eharris369 👍 . Checking the job's package name/class was what I was thinking of, but I have the same qualms that you do.

**Comment by eharris369** [comment]
After discussing this we decided that the best thing to do is to have a better message when this fails telling the user to wait for operations that may be holding on to resources to complete and then try deleting the project from the Project Explorer view.
https://github.com/eclipse/codewind-eclipse/pull/340

**Comment by mmulholl** [comment]
Problem has been addressed.
